#!/bin/sh
# The DNS container's entrypoint: turn whatever the operator mounted into
# /etc/unbound/blacklist.d/ into an unbound include file, then hand over to
# the resolver.
#
# The blacklist is the one thing in this image that is meant to change without
# a rebuild. Mount a file — one domain per line — and every name in it, with
# everything below it, stops resolving:
#
#   docker run ... -v ./my-blocklist.txt:/etc/unbound/blacklist.d/list.txt:ro ...
#
# Accepted lines, so an existing hosts file works as-is:
#
#   ads.example.com            a bare domain
#   0.0.0.0 tracker.example.net   hosts-file style, the address is ignored
#   # comment                  and blank lines, both skipped
#
# Each domain becomes a local-zone of type always_nxdomain: the resolver
# answers NXDOMAIN for the name and everything beneath it, from itself, with
# no upstream query ever leaving the container. NXDOMAIN rather than 0.0.0.0
# because a sinkholed address invites the client to retry, while a name that
# does not exist is simply done.
#
# Lines that are not domains are skipped with a count, not a crash: a 90k-line
# hosts file with three weird entries should lose those three, not take the
# tunnel's resolver down with it. The generated file always exists, even when
# nothing was mounted — an unbound include pointing at a missing file refuses
# to start, and the resolver must not become the newest single point of
# failure because the operator mounted nothing at all.
set -eu

BLACKLIST_DIR="${AWG_BLACKLIST_DIR:-/etc/unbound/blacklist.d}"
OUT="${AWG_BLACKLIST_OUT:-/tmp/blacklist.conf}"

tmp=$(mktemp)
domains=$(mktemp)
trap 'rm -f "$tmp" "$domains"' EXIT

# One pass per mounted file: strip hosts-file addresses, strip comments and
# whitespace, keep only lines that are plausibly domains. The validity check
# is deliberately narrow — lowercase letters, digits, dots, hyphens, and at
# least one dot — because everything this rejects is either a typo or not a
# domain, and unbound has its own opinions about the rest.
found=0
for f in "$BLACKLIST_DIR"/*; do
    [ -e "$f" ] || continue
    found=1
    sed -e 's/#.*$//' -e 's/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}[[:space:]]*//' \
        -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' "$f" || true
done > "$tmp"

grep -E '^[a-z0-9_-]+(\.[a-z0-9_-]+)+$' "$tmp" > "$domains" || true
sort -u -o "$domains" "$domains"

n=$(wc -l < "$domains" | tr -d ' ')
{
    echo "# generated by entrypoint-dns.sh from $BLACKLIST_DIR — do not edit"
    echo "# $(date -u '+%Y-%m-%dT%H:%M:%SZ'), $n domain(s)"
    while IFS= read -r d; do
        [ -n "$d" ] && printf 'local-zone: "%s" always_nxdomain\n' "$d"
    done < "$domains"
} > "$OUT"

skipped=$(( $(wc -l < "$tmp" | tr -d ' ') - n ))
[ "$skipped" -le 0 ] || echo "blacklist: skipped $skipped line(s) that were not domains" >&2
echo "blacklist: $n domain(s) will answer NXDOMAIN" >&2

exec /usr/sbin/unbound -d -p -c /etc/unbound/unbound.conf
