//! Turning one parameter set into a server config, a UAPI request and a client
//! `.conf`.
//!
//! The single most important property in this file is that all three come from
//! the *same* [`Tunnel`] value. AmneziaWG obfuscation is symmetric: the junk
//! packet counts, the magic headers, the padding range and the 3.0 header key
//! have to be byte-identical on both ends. When they are not, nothing reports an
//! error — the peers simply never recognise each other's packets and the
//! handshake times out. So there is one generator, two renderers, and a test
//! that reads both renderings back and compares them field by field.

use base64::{Engine as _, engine::general_purpose::STANDARD as B64};

use crate::awg3::{Awg3Options, Awg3Params, clamp_s_for_header_protection};
use crate::render::{awg3_conf_lines, awg3_uapi_lines};
use crate::rng::Rng;
use crate::{Error, Result};

/// Written into the server config in place of the private key, so the config
/// can be built (and tested) on this machine and completed on the target from a
/// key file that never leaves it.
pub const SERVER_KEY_PLACEHOLDER: &str = "__SERVER_PRIVATE_KEY__";

/// `MessageInitiationSize` and `MessageResponseSize` — `device/noise-protocol.go`.
/// They appear here only because of the S1/S2 collision rule below.
const MESSAGE_INITIATION_SIZE: u32 = 148;
const MESSAGE_RESPONSE_SIZE: u32 = 92;

/// S4 pads transport packets, and the protocol caps it at 32 bytes — every
/// client in `crate::versions::CLIENTS` refuses more, and so does the upstream
/// generator. S1–S3 have no such ceiling.
pub const MAX_S4: u32 = 32;

// ------------------------------------------------------------ 2.0 obfuscation

/// The pre-3.0 obfuscation knobs.
///
/// These are not generated by [`crate::awg3`], which owns the 3.0 block only —
/// but a 3.0 config that omits them is a 3.0 config with a stock WireGuard
/// handshake in front of it, which is exactly the thing DPI matches on. So they
/// are generated here, alongside the deployment that needs them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BaseObfuscation {
    /// Junk packets sent before the handshake, and their size bounds.
    pub jc: u32,
    pub jmin: u32,
    pub jmax: u32,
    /// Junk prepended to the four handshake message types, S1..S4.
    pub s: [u32; 4],
    /// Magic headers replacing the four WireGuard message type numbers, H1..H4.
    pub h: [u32; 4],
}

impl BaseObfuscation {
    /// `H1..H4` stand in for message types 1..4, so they have to avoid the
    /// values they replace and each other; the daemon demultiplexes on this
    /// number alone and two equal headers make one message type unreachable.
    const H_FLOOR: u32 = 5;
    const H_CEILING: u32 = 2_000_000_000;

    pub fn generate(rng: &mut impl Rng, header_protection: bool) -> Self {
        let jmin = rng.range(20, 60);
        let mut me = Self {
            jc: rng.range(3, 8),
            jmin,
            jmax: jmin + rng.range(30, 120),
            s: [0; 4],
            h: [0; 4],
        };

        for s in &mut me.s {
            // The floor is a floor, not a value: see clamp_s_for_header_protection.
            *s = clamp_s_for_header_protection(rng.range(4, 60), header_protection);
        }
        // The 4..60 draw is right for S1..S3 and out of range for S4, which the
        // protocol caps at MAX_S4.
        me.s[3] = me.s[3].min(MAX_S4);
        // The daemon refuses S1 + 148 == S2 + 92 (device/uapi.go) — an initiation
        // padded to exactly the size of a response would be ambiguous on the wire.
        if me.s[0] + MESSAGE_INITIATION_SIZE == me.s[1] + MESSAGE_RESPONSE_SIZE {
            me.s[1] += 1;
        }

        for i in 0..4 {
            loop {
                let candidate = rng.range(Self::H_FLOOR, Self::H_CEILING);
                if !me.h[..i].contains(&candidate) {
                    me.h[i] = candidate;
                    break;
                }
            }
        }
        me
    }

    /// The invariants a hand-edited or externally supplied set can break.
    pub fn validate(&self) -> Result<()> {
        if self.jmin > self.jmax {
            return Err(Error::Invariant(format!(
                "Jmin ({}) must not exceed Jmax ({})",
                self.jmin, self.jmax
            )));
        }
        for (i, h) in self.h.iter().enumerate() {
            if *h < Self::H_FLOOR {
                return Err(Error::Invariant(format!(
                    "H{} ({h}) collides with a WireGuard message type; it must be >= {}",
                    i + 1,
                    Self::H_FLOOR
                )));
            }
            if self.h[..i].contains(h) {
                return Err(Error::Invariant(format!(
                    "H{} ({h}) repeats an earlier magic header; the peer cannot tell the two message types apart",
                    i + 1
                )));
            }
        }
        if self.s[3] > MAX_S4 {
            return Err(Error::Invariant(format!(
                "S4 ({}) exceeds the protocol maximum of {MAX_S4}",
                self.s[3]
            )));
        }
        if self.s[0] + MESSAGE_INITIATION_SIZE == self.s[1] + MESSAGE_RESPONSE_SIZE {
            return Err(Error::Invariant(format!(
                "S1 ({}) + {MESSAGE_INITIATION_SIZE} must not equal S2 ({}) + {MESSAGE_RESPONSE_SIZE}; the daemon rejects it",
                self.s[0], self.s[1]
            )));
        }
        Ok(())
    }

    /// `.conf` spelling.
    pub fn conf_lines(&self) -> Vec<String> {
        let mut out = vec![
            format!("Jc = {}", self.jc),
            format!("Jmin = {}", self.jmin),
            format!("Jmax = {}", self.jmax),
        ];
        for (i, v) in self.s.iter().enumerate() {
            out.push(format!("S{} = {v}", i + 1));
        }
        for (i, v) in self.h.iter().enumerate() {
            out.push(format!("H{} = {v}", i + 1));
        }
        out
    }

    /// UAPI spelling — same numbers, lowercase keys, `key=value` with no spaces.
    pub fn uapi_lines(&self) -> Vec<String> {
        let mut out = vec![
            format!("jc={}", self.jc),
            format!("jmin={}", self.jmin),
            format!("jmax={}", self.jmax),
        ];
        for (i, v) in self.s.iter().enumerate() {
            out.push(format!("s{}={v}", i + 1));
        }
        for (i, v) in self.h.iter().enumerate() {
            out.push(format!("h{}={v}", i + 1));
        }
        out
    }
}

/// Everything both ends of one tunnel have to agree on.
#[derive(Debug, Clone)]
pub struct Tunnel {
    pub base: BaseObfuscation,
    pub awg3: Awg3Params,
}

impl Tunnel {
    /// Generate one tunnel's worth of obfuscation. Called once per deploy: a
    /// shared parameter set would give every install the same DPI fingerprint.
    pub fn generate(rng: &mut impl Rng, opts: Awg3Options) -> Result<Self> {
        let awg3 = crate::awg3::generate(rng, opts)?;
        let base = BaseObfuscation::generate(rng, opts.header_protection);
        base.validate()?;
        Ok(Self { base, awg3 })
    }

    fn conf_lines(&self) -> Vec<String> {
        let mut out = self.base.conf_lines();
        out.extend(awg3_conf_lines(&self.awg3));
        out
    }

    fn uapi_lines(&self) -> Vec<String> {
        let mut out = self.base.uapi_lines();
        out.extend(awg3_uapi_lines(&self.awg3));
        out
    }
}

// ------------------------------------------------------------------- network

/// Addresses and ports — everything about the tunnel that is not obfuscation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NetworkSpec {
    pub interface: String,
    pub listen_port: u16,
    /// The server's own address inside the tunnel, with the prefix that defines
    /// the tunnel subnet.
    pub server_address: String,
    /// The client's address, as a host route.
    pub client_address: String,
    /// What goes into the client's `Endpoint`.
    pub endpoint_host: String,
    pub dns: Vec<String>,
    pub mtu: u16,
    pub allowed_ips: Vec<String>,
    pub persistent_keepalive: u16,
}

impl Default for NetworkSpec {
    fn default() -> Self {
        Self {
            interface: "awg0".into(),
            listen_port: 51820,
            server_address: "10.8.1.1/24".into(),
            client_address: "10.8.1.2/32".into(),
            endpoint_host: String::new(),
            dns: vec!["1.1.1.1".into(), "8.8.8.8".into()],
            // 1420 leaves room for the WireGuard header inside a 1500 byte path;
            // AmneziaWG's junk adds nothing to the transport packet itself.
            mtu: 1420,
            allowed_ips: vec!["0.0.0.0/0".into(), "::/0".into()],
            // Behind NAT the mapping expires in well under a minute of silence.
            persistent_keepalive: 25,
        }
    }
}

impl NetworkSpec {
    pub fn endpoint(&self) -> String {
        // An IPv6 literal needs brackets or the port cannot be told from the
        // address — the same reason vpn.rs splits on the *last* colon.
        if self.endpoint_host.contains(':') && !self.endpoint_host.starts_with('[') {
            format!("[{}]:{}", self.endpoint_host, self.listen_port)
        } else {
            format!("{}:{}", self.endpoint_host, self.listen_port)
        }
    }
}

/// The key material of one peering. The server's private key is deliberately
/// absent: it is generated on the target and never leaves it, and the config
/// carries [`SERVER_KEY_PLACEHOLDER`] until the target substitutes it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Keys {
    pub server_public: String,
    pub client_private: String,
    pub client_public: String,
    pub preshared: Option<String>,
}

// ----------------------------------------------------------------- rendering

/// The server-side `.conf` the container's entrypoint reads.
pub fn server_conf(net: &NetworkSpec, tunnel: &Tunnel, keys: &Keys) -> String {
    let mut out = vec![
        "# AmneziaWG 3.0 server — generated by awg-tool, do not edit by hand.".into(),
        "[Interface]".into(),
        format!("PrivateKey = {SERVER_KEY_PLACEHOLDER}"),
        format!("Address = {}", net.server_address),
        format!("ListenPort = {}", net.listen_port),
        format!("MTU = {}", net.mtu),
    ];
    out.extend(tunnel.conf_lines());
    out.push(String::new());
    out.push("[Peer]".into());
    out.push(format!("PublicKey = {}", keys.client_public));
    if let Some(psk) = &keys.preshared {
        out.push(format!("PresharedKey = {psk}"));
    }
    out.push(format!("AllowedIPs = {}", net.client_address));
    out.push(String::new());
    out.join("\n")
}

/// The `.conf` handed to the user, and the input to [`crate::vpn::conf_to_vpn`].
pub fn client_conf(net: &NetworkSpec, tunnel: &Tunnel, keys: &Keys) -> String {
    let mut out = vec![
        "[Interface]".into(),
        format!("PrivateKey = {}", keys.client_private),
        format!("Address = {}", net.client_address),
        format!("DNS = {}", net.dns.join(", ")),
        format!("MTU = {}", net.mtu),
    ];
    out.extend(tunnel.conf_lines());
    out.push(String::new());
    out.push("[Peer]".into());
    out.push(format!("PublicKey = {}", keys.server_public));
    if let Some(psk) = &keys.preshared {
        out.push(format!("PresharedKey = {psk}"));
    }
    out.push(format!("AllowedIPs = {}", net.allowed_ips.join(", ")));
    out.push(format!("Endpoint = {}", net.endpoint()));
    out.push(format!(
        "PersistentKeepalive = {}",
        net.persistent_keepalive
    ));
    out.push(String::new());
    out.join("\n")
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Base64 key material as UAPI wants it: lowercase hex.
fn key_to_hex(b64: &str, what: &str) -> Result<String> {
    let raw = B64
        .decode(b64.trim())
        .map_err(|e| Error::Key(format!("{what} is not base64: {e}")))?;
    if raw.len() != 32 {
        return Err(Error::Key(format!(
            "{what} decodes to {} bytes, not 32 — a truncated key still handshakes with itself and nothing else",
            raw.len()
        )));
    }
    Ok(hex(&raw))
}

/// The `set=1` request that configures the server device.
///
/// This is what the container's entrypoint assembles from the server `.conf`;
/// building it here as well is what makes the agreement between the two
/// renderings checkable offline. `server_private_key` is base64, as `awg genkey`
/// prints it.
pub fn server_uapi_request(
    net: &NetworkSpec,
    tunnel: &Tunnel,
    keys: &Keys,
    server_private_key: &str,
) -> Result<String> {
    let mut out = vec!["set=1".to_string()];
    out.push(format!(
        "private_key={}",
        key_to_hex(server_private_key, "the server private key")?
    ));
    out.push(format!("listen_port={}", net.listen_port));
    out.extend(tunnel.uapi_lines());

    out.push("replace_peers=true".into());
    out.push(format!(
        "public_key={}",
        key_to_hex(&keys.client_public, "the client public key")?
    ));
    if let Some(psk) = &keys.preshared {
        out.push(format!(
            "preshared_key={}",
            key_to_hex(psk, "the preshared key")?
        ));
    }
    out.push("replace_allowed_ips=true".into());
    out.push(format!("allowed_ip={}", net.client_address));

    // A UAPI request is terminated by an empty line; without it the daemon keeps
    // reading and the write appears to hang.
    out.push(String::new());
    out.push(String::new());
    Ok(out.join("\n"))
}

// ----------------------------------------------------------------- container

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerSpec {
    pub image: String,
    pub name: String,
    /// Host directory bind-mounted at [`Self::CONF_MOUNT`].
    pub conf_dir: String,
    pub restart: String,
}

impl ContainerSpec {
    pub const CONF_MOUNT: &'static str = "/etc/amnezia/awg3";
    pub const CONF_NAME: &'static str = "server.conf";

    pub fn conf_path(&self) -> String {
        format!(
            "{}/{}",
            self.conf_dir.trim_end_matches('/'),
            Self::CONF_NAME
        )
    }
}

impl Default for ContainerSpec {
    fn default() -> Self {
        Self {
            // A published name, not a local one. `awg3-server:latest` only
            // exists on a machine that built it, and it also defeats the
            // detection in `crate::docker`, which recognises our containers by
            // image reference before falling back to a label.
            image: "vaiprog/amnezia-wg-3:latest".into(),
            name: "awg3-server".into(),
            conf_dir: "/etc/amnezia/awg3".into(),
            restart: "unless-stopped".into(),
        }
    }
}

/// The `docker run` that starts the server.
///
/// `NET_ADMIN` plus `/dev/net/tun` and nothing else: amneziawg-go is a userspace
/// implementation, so it needs to create a TUN device and write firewall rules,
/// but it has no business with `--privileged` or the host network namespace. The
/// port is published rather than shared, which keeps the container's own
/// iptables rules out of the host's tables.
pub fn docker_run_command(spec: &ContainerSpec, net: &NetworkSpec) -> String {
    let mut a: Vec<String> = vec![
        "docker run -d".into(),
        format!("--name {}", spec.name),
        format!("--restart {}", spec.restart),
        "--cap-add NET_ADMIN".into(),
        "--device /dev/net/tun".into(),
        "--sysctl net.ipv4.ip_forward=1".into(),
        format!("-p {}:{}/udp", net.listen_port, net.listen_port),
        format!(
            "-v {}:{}:ro",
            spec.conf_dir.trim_end_matches('/'),
            ContainerSpec::CONF_MOUNT
        ),
        // Peer records and the boot counter. Without these the container is
        // stateless in the worst way: recreating it silently revokes every peer
        // `awg-peer` ever issued, and the only symptom is clients that quietly
        // stop handshaking.
        format!("-v {}-state:/var/lib/awg", spec.name),
        format!("-v {}-log:/var/log/awg", spec.name),
        format!("-e AWG_IFACE={}", net.interface),
        format!(
            "-e AWG_CONF={}/{}",
            ContainerSpec::CONF_MOUNT,
            ContainerSpec::CONF_NAME
        ),
        // Without this, configs issued by `awg-peer` inside the container carry
        // a literal SERVER_PUBLIC_IP placeholder as their endpoint. The deploy
        // already knows the real address, so there is no reason to make the
        // operator paste it in afterwards.
        format!("-e AWG_ENDPOINT={}", net.endpoint()),
    ];
    a.push(spec.image.clone());
    a.join(" ")
}

/// Remove any previous container of the same name. `|| true` because "not
/// there" is the expected case on a first deploy, not a failure.
pub fn docker_reset_command(spec: &ContainerSpec) -> String {
    format!("docker rm -f {} >/dev/null 2>&1 || true", spec.name)
}

pub fn docker_logs_command(spec: &ContainerSpec) -> String {
    format!("docker logs --tail 50 {}", spec.name)
}

/// Ask the container's own namespace whether the interface exists and is up.
pub fn interface_check_command(spec: &ContainerSpec, net: &NetworkSpec) -> String {
    format!(
        "docker exec {} ip -o link show {}",
        spec.name, net.interface
    )
}

/// Did the interface actually come up?
///
/// A WireGuard device sits at `state UNKNOWN` forever — it has no carrier to
/// report — so the only meaningful signal is the `UP` flag, and it has to be
/// matched as a whole word: `LOWER_UP` contains it as a substring.
pub fn parse_interface_up(output: &str, interface: &str) -> bool {
    output.lines().any(|line| {
        let Some((head, rest)) = line.split_once('<') else {
            return false;
        };
        if !head
            .split_whitespace()
            .any(|t| t.trim_end_matches(':') == interface)
        {
            return false;
        }
        let Some((flags, _)) = rest.split_once('>') else {
            return false;
        };
        flags.split(',').any(|f| f == "UP")
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rng::SeededRng;
    use std::collections::BTreeMap;

    fn keys() -> Keys {
        Keys {
            server_public: "0RSyG3nCXLBLGvNGqIzfhAqxV5s+RBgs1cq5AhCUcng=".into(),
            client_private: "yNMDBJ4Vd3nZuJ2FZ1ChNTvHNQg1KgLpOaOtQC8LSXY=".into(),
            client_public: "7DHFY2VYRZ7Ag+K7C6X0i9FfHkw+q4H0dqIiRCyEXHM=".into(),
            preshared: Some("dGVzdHBza3Rlc3Rwc2t0ZXN0cHNrdGVzdHBza3Rlc3Q=".into()),
        }
    }

    const SERVER_PRIVATE: &str = "cGxhY2Vob2xkZXJzZXJ2ZXJwcml2YXRla2V5MzJieXQ=";

    fn spec() -> NetworkSpec {
        NetworkSpec {
            endpoint_host: "95.85.30.7".into(),
            ..Default::default()
        }
    }

    fn tunnel(seed: u64) -> Tunnel {
        Tunnel::generate(&mut SeededRng::new(seed), Awg3Options::default()).unwrap()
    }

    /// `Key = value` out of a `.conf`, restricted to the `[Interface]` block.
    fn interface_block(conf: &str) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        let mut inside = false;
        for line in conf.lines() {
            let line = line.split('#').next().unwrap_or("").trim();
            if line.starts_with('[') {
                inside = line.eq_ignore_ascii_case("[Interface]");
                continue;
            }
            if !inside || line.is_empty() {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                out.insert(k.trim().to_string(), v.trim().to_string());
            }
        }
        out
    }

    /// `key=value` out of a UAPI request, up to the first peer.
    fn uapi_device_block(req: &str) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        for line in req.lines() {
            if line.starts_with("public_key=") {
                break;
            }
            if let Some((k, v)) = line.split_once('=') {
                out.insert(k.to_string(), v.to_string());
            }
        }
        out
    }

    // -------------------------------------------------- the agreement test

    #[test]
    fn the_server_uapi_request_and_the_client_conf_carry_identical_obfuscation() {
        // If these ever drift the tunnel does not fail — it just never completes
        // a handshake, with no error on either side. So compare every field.
        for seed in 0..200u64 {
            let t = tunnel(seed);
            let net = spec();
            let conf = interface_block(&client_conf(&net, &t, &keys()));
            let uapi =
                uapi_device_block(&server_uapi_request(&net, &t, &keys(), SERVER_PRIVATE).unwrap());

            let numeric = [
                ("Jc", "jc"),
                ("Jmin", "jmin"),
                ("Jmax", "jmax"),
                ("S1", "s1"),
                ("S2", "s2"),
                ("S3", "s3"),
                ("S4", "s4"),
                ("H1", "h1"),
                ("H2", "h2"),
                ("H3", "h3"),
                ("H4", "h4"),
                ("ContentPaddingAddition", "content_padding_addition"),
                ("RekeyAfterTime", "rekey_after_time"),
                ("RekeyTimeout", "rekey_timeout"),
                ("RejectAfterTime", "reject_after_time"),
                ("KeepaliveTimeout", "keepalive_timeout"),
                ("MaxHandshakeAttempts", "max_handshake_attempts"),
            ];
            for (conf_key, uapi_key) in numeric {
                let c = conf
                    .get(conf_key)
                    .unwrap_or_else(|| panic!("{conf_key} missing from the client .conf"));
                let u = uapi
                    .get(uapi_key)
                    .unwrap_or_else(|| panic!("{uapi_key} missing from the server UAPI request"));
                assert_eq!(c, u, "seed {seed}: {conf_key} ({c}) != {uapi_key} ({u})");
            }

            // The one field whose *encoding* differs: base64 in .conf, hex over
            // UAPI. Compare the bytes, not the text.
            let conf_key = B64
                .decode(
                    conf.get("HeaderProtectionKey")
                        .expect("no HeaderProtectionKey"),
                )
                .unwrap();
            assert_eq!(
                hex(&conf_key),
                *uapi
                    .get("header_protection_key")
                    .expect("no header_protection_key"),
                "seed {seed}: header protection keys differ"
            );
            assert_eq!(conf_key.len(), 32);
        }
    }

    #[test]
    fn the_server_conf_and_the_client_conf_carry_identical_obfuscation() {
        // Same invariant one step earlier: the container builds its UAPI request
        // from this file, so a mismatch here reaches the wire just as silently.
        let t = tunnel(3);
        let net = spec();
        let server = interface_block(&server_conf(&net, &t, &keys()));
        let client = interface_block(&client_conf(&net, &t, &keys()));
        for key in [
            "Jc",
            "Jmin",
            "Jmax",
            "S1",
            "S2",
            "S3",
            "S4",
            "H1",
            "H2",
            "H3",
            "H4",
            "HeaderProtectionKey",
            "ContentPaddingAddition",
            "RekeyAfterTime",
            "RekeyTimeout",
            "RejectAfterTime",
            "KeepaliveTimeout",
            "MaxHandshakeAttempts",
            "MTU",
        ] {
            assert_eq!(
                server.get(key),
                client.get(key),
                "{key} differs between the two configs"
            );
        }
    }

    #[test]
    fn generated_base_obfuscation_always_satisfies_its_invariants() {
        for seed in 0..500u64 {
            let base = BaseObfuscation::generate(&mut SeededRng::new(seed), true);
            base.validate()
                .expect("generator must not emit what validate rejects");
            assert!(
                base.s.iter().all(|s| *s >= 12),
                "S floor for header protection"
            );
            let mut sorted = base.h.to_vec();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(sorted.len(), 4, "magic headers must be distinct");
        }
    }

    #[test]
    fn the_s_floor_applies_only_when_header_protection_is_on() {
        // The floor exists because the header cipher takes its nonce from the
        // padding; with no header key there is no nonce and no floor. Proving
        // the clamp is load-bearing means showing values below it do occur when
        // it is off.
        let below: usize = (0..200u64)
            .map(|seed| BaseObfuscation::generate(&mut SeededRng::new(seed), false))
            .flat_map(|b| b.s.into_iter().collect::<Vec<_>>())
            .filter(|s| *s < 12)
            .count();
        assert!(
            below > 0,
            "the clamp would be untested if S never fell below the floor"
        );

        for seed in 0..200u64 {
            let on = BaseObfuscation::generate(&mut SeededRng::new(seed), true);
            assert!(
                on.s.iter().all(|s| *s >= 12),
                "seed {seed}: S below the nonce floor"
            );
        }
    }

    #[test]
    fn validate_rejects_repeated_or_reserved_magic_headers() {
        let mut base = BaseObfuscation::generate(&mut SeededRng::new(1), true);
        base.h[2] = base.h[0];
        assert!(base.validate().is_err(), "duplicate H must be refused");

        let mut base = BaseObfuscation::generate(&mut SeededRng::new(1), true);
        base.h[0] = 4; // a real WireGuard message type
        assert!(base.validate().is_err());
    }

    #[test]
    fn validate_rejects_the_s1_s2_size_collision_the_daemon_refuses() {
        let mut base = BaseObfuscation::generate(&mut SeededRng::new(2), true);
        base.s[0] = 30;
        base.s[1] = 30 + 56; // S1 + 148 == S2 + 92
        assert!(base.validate().is_err());
        base.s[1] += 1;
        assert!(base.validate().is_ok());
    }

    #[test]
    fn validate_rejects_an_inverted_junk_size_range() {
        let mut base = BaseObfuscation::generate(&mut SeededRng::new(4), true);
        base.jmin = 500;
        base.jmax = 40;
        assert!(base.validate().is_err());
    }

    #[test]
    fn the_server_config_never_contains_a_private_key() {
        let conf = server_conf(&spec(), &tunnel(5), &keys());
        assert!(conf.contains(SERVER_KEY_PLACEHOLDER));
        // The client's private key belongs only in the client config.
        assert!(!conf.contains(&keys().client_private));
        assert!(conf.contains(&keys().client_public));
    }

    #[test]
    fn the_client_config_has_everything_a_client_needs_to_connect() {
        let conf = client_conf(&spec(), &tunnel(6), &keys());
        for expected in [
            "Endpoint = 95.85.30.7:51820",
            "AllowedIPs = 0.0.0.0/0, ::/0",
            "PersistentKeepalive = 25",
            "DNS = 1.1.1.1, 8.8.8.8",
            "Address = 10.8.1.2/32",
        ] {
            assert!(conf.contains(expected), "missing {expected} in:\n{conf}");
        }
        assert!(conf.contains(&keys().server_public));
    }

    #[test]
    fn an_ipv6_endpoint_is_bracketed_so_the_port_can_be_found() {
        let net = NetworkSpec {
            endpoint_host: "2001:db8::1".into(),
            ..Default::default()
        };
        assert_eq!(net.endpoint(), "[2001:db8::1]:51820");
    }

    #[test]
    fn the_uapi_request_is_terminated_by_a_blank_line() {
        let req = server_uapi_request(&spec(), &tunnel(7), &keys(), SERVER_PRIVATE).unwrap();
        assert!(req.starts_with("set=1\n"));
        assert!(
            req.ends_with("\n\n"),
            "an unterminated request makes the daemon wait forever"
        );
        assert!(req.contains("replace_peers=true"));
        assert!(req.contains("allowed_ip=10.8.1.2/32"));
        assert!(req.contains("listen_port=51820"));
    }

    #[test]
    fn uapi_rendering_refuses_key_material_that_is_not_a_32_byte_key() {
        let net = spec();
        let t = tunnel(8);
        assert!(server_uapi_request(&net, &t, &keys(), "not base64!!").is_err());
        assert!(server_uapi_request(&net, &t, &keys(), "c2hvcnQ=").is_err());
    }

    #[test]
    fn the_docker_run_command_asks_for_exactly_the_privileges_it_needs() {
        let cmd = docker_run_command(&ContainerSpec::default(), &spec());
        for expected in [
            "docker run -d",
            "--name awg3-server",
            "--restart unless-stopped",
            "--cap-add NET_ADMIN",
            "--device /dev/net/tun",
            "--sysctl net.ipv4.ip_forward=1",
            "-p 51820:51820/udp",
            "-v /etc/amnezia/awg3:/etc/amnezia/awg3:ro",
            // Peers survive `docker rm` only because of these two.
            "-v awg3-server-state:/var/lib/awg",
            "-v awg3-server-log:/var/log/awg",
            "-e AWG_IFACE=awg0",
            "-e AWG_CONF=/etc/amnezia/awg3/server.conf",
            "-e AWG_ENDPOINT=95.85.30.7:51820",
            "vaiprog/amnezia-wg-3:latest",
        ] {
            assert!(cmd.contains(expected), "missing {expected} in: {cmd}");
        }
        assert!(!cmd.contains("--privileged"), "privileged is never needed");
        assert!(!cmd.contains("--network host"));
        // The image must be the last word or docker reads it as an argument.
        assert!(cmd.ends_with("vaiprog/amnezia-wg-3:latest"));
    }

    #[test]
    fn the_default_image_is_one_that_actually_exists_and_is_recognised() {
        // Two separate reasons, both learned the hard way: a local-only tag
        // cannot be pulled on a fresh host, and container detection matches the
        // image reference before it falls back to a label.
        let spec = ContainerSpec::default();
        assert!(spec.image.starts_with("vaiprog/amnezia-wg-"));
        assert!(
            crate::docker::parse_image_ref(&spec.image)
                .map(|r| r.is_awg())
                .unwrap_or(false),
            "the deploy default must be detectable as one of ours"
        );
    }

    #[test]
    fn a_custom_container_spec_reaches_every_part_of_the_command() {
        let spec_c = ContainerSpec {
            image: "ghcr.io/example/awg3:v1".into(),
            name: "vpn".into(),
            conf_dir: "/srv/awg/".into(),
            restart: "always".into(),
        };
        let net = NetworkSpec {
            listen_port: 4443,
            interface: "awg9".into(),
            ..spec()
        };
        let cmd = docker_run_command(&spec_c, &net);
        assert!(cmd.contains("-v /srv/awg:/etc/amnezia/awg3:ro"), "{cmd}");
        assert!(cmd.contains("-p 4443:4443/udp"));
        assert!(cmd.contains("-e AWG_IFACE=awg9"));
        assert!(cmd.ends_with("ghcr.io/example/awg3:v1"));
        assert_eq!(spec_c.conf_path(), "/srv/awg/server.conf");
        assert_eq!(
            docker_reset_command(&spec_c),
            "docker rm -f vpn >/dev/null 2>&1 || true"
        );
        assert_eq!(docker_logs_command(&spec_c), "docker logs --tail 50 vpn");
        assert_eq!(
            interface_check_command(&spec_c, &net),
            "docker exec vpn ip -o link show awg9"
        );
    }

    #[test]
    fn interface_state_is_read_from_the_flags_not_from_state_unknown() {
        // Real `ip -o link show awg0` for a userspace WireGuard device.
        let up = "5: awg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500\\    link/none";
        assert!(parse_interface_up(up, "awg0"));
        assert!(
            !parse_interface_up(up, "awg1"),
            "another device must not count"
        );

        let down = "5: awg0: <POINTOPOINT,NOARP> mtu 1420 qdisc noop state DOWN mode DEFAULT group default qlen 500\\    link/none";
        assert!(!parse_interface_up(down, "awg0"));

        // LOWER_UP alone is not UP — substring matching would get this wrong.
        let lower_only = "5: awg0: <POINTOPOINT,NOARP,LOWER_UP> mtu 1420 state UNKNOWN";
        assert!(!parse_interface_up(lower_only, "awg0"));

        assert!(!parse_interface_up(
            "Device \"awg0\" does not exist.",
            "awg0"
        ));
        assert!(!parse_interface_up("", "awg0"));
    }

    #[test]
    fn every_interface_line_a_client_needs_survives_into_the_vpn_link() {
        // The link is what most users actually import, so the round trip through
        // vpn.rs has to keep the obfuscation intact.
        let t = tunnel(12);
        let conf = client_conf(&spec(), &t, &keys());
        let link = crate::vpn::conf_to_vpn(&conf).unwrap();
        assert!(link.starts_with("vpn://"));
        let decoded = crate::vpn::decode(&link).unwrap();
        let awg = &decoded["containers"][0]["awg"];
        assert_eq!(awg["config"].as_str().unwrap(), conf);
        assert_eq!(awg["Jc"].as_str().unwrap(), t.base.jc.to_string());
    }

    // ------------------------------------------------ once per server, not per client
    //
    // The obfuscation block is a *shared secret between the two ends*, not a
    // per-client credential. Both peers must present the identical block or
    // they never recognise each other's packets and the handshake times out
    // with no error anywhere. So randomising it per client would be the bug —
    // these tests pin the correct behaviour rather than describing an intent.

    /// The fields `conf_obfuscation` in `containers/awg-peer` copies verbatim
    /// out of the server config into every issued client config.
    ///
    /// Pinned here because that shell function and this renderer have to agree.
    /// A field the renderer emits and the grep misses is a field the client
    /// never receives — and, again, a handshake that simply never completes.
    const PEER_TOOL_FIELDS: [&str; 24] = [
        "H1",
        "H2",
        "H3",
        "H4",
        "S1",
        "S2",
        "S3",
        "S4",
        "Jc",
        "Jmin",
        "Jmax",
        "I1",
        "I2",
        "I3",
        "I4",
        "I5",
        "Itime",
        "HeaderProtectionKey",
        "ContentPaddingAddition",
        "RekeyAfterTime",
        "RekeyTimeout",
        "RejectAfterTime",
        "KeepaliveTimeout",
        "MaxHandshakeAttempts",
    ];

    fn key_material(seed: u8) -> String {
        B64.encode([seed; 32])
    }

    /// One client's worth of credentials, all of them distinct from every other
    /// client's.
    fn client_keys(n: u8) -> Keys {
        Keys {
            server_public: key_material(200),
            client_private: key_material(n * 3 + 1),
            client_public: key_material(n * 3 + 2),
            preshared: Some(key_material(n * 3 + 3)),
        }
    }

    fn client_net(n: u8) -> NetworkSpec {
        NetworkSpec {
            client_address: format!("10.8.1.{}/32", 2 + n),
            ..spec()
        }
    }

    #[test]
    fn every_client_of_one_server_is_issued_the_identical_obfuscation_block() {
        let t = tunnel(21);
        let server =
            crate::docker::obfuscation_from_conf(&server_conf(&spec(), &t, &client_keys(0)));
        assert_eq!(
            server.len(),
            18,
            "the 3.0 block is Jc/Jmin/Jmax, S1-S4, H1-H4, the header key, the padding range \
             and five timer ranges"
        );
        for n in 0..6u8 {
            let issued = crate::docker::obfuscation_from_conf(&client_conf(
                &client_net(n),
                &t,
                &client_keys(n),
            ));
            assert_eq!(
                issued, server,
                "client {n} was issued a different obfuscation block from the server's"
            );
        }
    }

    #[test]
    fn every_client_of_one_server_gets_its_own_credentials() {
        let t = tunnel(22);
        let confs: Vec<String> = (0..6u8)
            .map(|n| client_conf(&client_net(n), &t, &client_keys(n)))
            .collect();

        // PresharedKey lives in [Peer] and the other two in [Interface], so
        // this reads the whole file rather than one section of it.
        let value = |conf: &str, field: &str| -> String {
            conf.lines()
                .filter_map(|l| l.split_once('='))
                .find(|(k, _)| k.trim() == field)
                .map(|(_, v)| v.trim().to_string())
                .unwrap_or_else(|| panic!("no {field} in the issued config"))
        };
        for field in ["PrivateKey", "PresharedKey", "Address"] {
            let unique: std::collections::BTreeSet<String> =
                confs.iter().map(|c| value(c, field)).collect();
            assert_eq!(unique.len(), confs.len(), "{field} repeats between clients");
        }

        // And one client's config never carries another's private key.
        for (i, conf) in confs.iter().enumerate() {
            for (j, other) in confs.iter().enumerate() {
                if i == j {
                    continue;
                }
                let secret = interface_block(other)["PrivateKey"].clone();
                assert!(
                    !conf.contains(&secret),
                    "client {i}'s config carries client {j}'s private key"
                );
            }
        }
    }

    #[test]
    fn two_installs_do_not_share_a_fingerprint() {
        // Per *server*, not global: a shared parameter set would give every
        // install built with this tool one DPI fingerprint.
        let a = crate::docker::obfuscation_from_conf(&client_conf(&spec(), &tunnel(31), &keys()));
        let b = crate::docker::obfuscation_from_conf(&client_conf(&spec(), &tunnel(32), &keys()));
        assert_ne!(a, b);
    }

    #[test]
    fn the_shell_peer_tool_copies_every_field_the_renderer_emits() {
        // `awg-peer add` reissues the block by grepping the server config. If
        // the renderer ever grows a field that grep does not name, the field
        // silently stops reaching clients.
        let server = interface_block(&server_conf(&spec(), &tunnel(33), &keys()));
        let per_node = ["PrivateKey", "Address", "ListenPort", "MTU"];
        for key in server.keys() {
            assert!(
                per_node.contains(&key.as_str()) || PEER_TOOL_FIELDS.contains(&key.as_str()),
                "{key} is in the server config but containers/awg-peer does not copy it"
            );
        }
        // ...and the shared block is not empty by accident.
        assert!(
            server
                .keys()
                .filter(|k| PEER_TOOL_FIELDS.contains(&k.as_str()))
                .count()
                >= 18
        );
    }
}
